import {runMatch} from '../engine/corewar-vm.mjs';
import {describeWarrior, genomeHash, genomeDistance} from '../engine/describe-warrior.mjs';
import {describeBout} from '../engine/describe-bout.mjs';

export const DEFAULT_RETENTION_POLICY={schemaVersion:1,broadCompetitors:5,counterSlots:1,outlierSlots:1,humanFavoredSlots:1,nearDuplicateDistance:0.18,counterBoutSeeds:['a','b','c','d'],counterMinWins:3,outlierMinDistance:0.45,outlierMinTiesOrWins:1};
export function recordString(r={}){return `${r.wins||0}W / ${r.ties||0}D / ${r.losses||0}L`;}
export function balancedSeries(candidate,opponent,{profileId,seeds=DEFAULT_RETENTION_POLICY.counterBoutSeeds}){const record={wins:0,losses:0,ties:0}, bouts=[]; for(const s of seeds){for(const order of [0,1]){const ws=order?[opponent,candidate]:[candidate,opponent]; const m=runMatch({profileId,warriors:ws,seed:`counter-${candidate.id}-${opponent.id}-${s}-${order}`,recordEvents:true}); const candWinner=m.winner===null?null:(order?1-m.winner:m.winner); if(candWinner===0) record.wins++; else if(candWinner===1) record.losses++; else record.ties++; bouts.push({...describeBout(m),seed:m.seed,order:order?'opponent-left':'candidate-left'});}} return {opponentId:opponent.id,opponentName:opponent.displayName||opponent.name||opponent.id,bouts:bouts.length,record,boutsDetail:bouts};}
export function dedupeByGenome(candidates,previous=[]){const seen=new Map(); const out=[]; const duplicates=[]; for(const w of [...previous,...candidates]){const hash=genomeHash(w); if(seen.has(hash)){const first=seen.get(hash); first.duplicateProvenance??={firstSeen:{id:first.id,generation:first.generation},alsoAppearedAs:[]}; first.duplicateProvenance.alsoAppearedAs.push({id:w.id,generation:w.generation,parentIds:w.parentIds||[]}); duplicates.push({id:w.id,genomeHash:hash,status:'archived',retirementReason:`exact normalized genome duplicate of ${first.id}`,duplicateOf:first.id,currentLeagueRank:w.currentLeagueRank,record:w.record}); continue;} const copy={...w,genomeHash:hash}; seen.set(hash,copy); if(!previous.includes(w)) out.push(copy);} return Object.assign(out,{duplicates});}
function nearDuplicateOf(w,selected,policy){return selected.find(x=>genomeDistance(x,w)<policy.nearDuplicateDistance && (x.parentIds||[]).some(id=>(w.parentIds||[]).includes(id)));}
export function selectRetained({scored,parents=[],benchmarks=[],profileId,policy=DEFAULT_RETENTION_POLICY,humanFavored=[]}){
  const deduped=dedupeByGenome(scored,[]); const candidates=deduped.map((w,i)=>({...w,currentLeagueRank:i+1,semantic:describeWarrior(w),status:'candidate'}));
  const selected=[]; const retired=[...(deduped.duplicates||[])]; const add=(w,reason,evidence)=>{if(selected.length>=policy.populationSize) return {ok:false,cause:'active roster cutoff'}; if(selected.some(x=>x.genomeHash===w.genomeHash||x.id===w.id)) return {ok:false,cause:`already retained as ${w.id}`}; const near=nearDuplicateOf(w,selected,policy); if(near) return {ok:false,cause:`near-duplicate pressure against retained ${near.id}`}; selected.push({...w,status:'active',retentionReason:reason,selectionEvidence:evidence}); return {ok:true};};
  for(const w of candidates.slice(0,policy.broadCompetitors)) add(w,'retained as broad competitor',{currentLeagueRecord:w.record,benchmarkRecord:w.benchmarkRecord,currentLeagueRank:w.currentLeagueRank,summary:`current league record: ${recordString(w.record)}; benchmark record: ${recordString(w.benchmarkRecord)}`});
  const leader=selected[0]||candidates[0]; let counters=0; for(const w of candidates){if(!leader||w.id===leader.id||counters>=policy.counterSlots) continue; const series=balancedSeries(w,leader,{profileId,seeds:policy.counterBoutSeeds}); const result=series.record.wins>=policy.counterMinWins && series.record.wins>series.record.losses ? add(w,'retained as champion counter',{against:series,overallRank:w.currentLeagueRank,summary:`vs ${series.opponentName}: ${recordString(series.record)} across ${series.bouts} balanced bouts; overall league rank #${w.currentLeagueRank}`}) : {ok:false}; if(result.ok) counters++;}
  let outliers=0; for(const w of candidates){if(outliers>=policy.outlierSlots) break; const minDistance=Math.min(...parents.map(p=>genomeDistance(w,p)),1); const viable=(w.record?.wins||0)+(w.record?.ties||0)>=policy.outlierMinTiesOrWins; const peak=w.replays?.[0]?describeBout(w.replays[0]).peakProcessCounts[0]:0; if(viable && minDistance>=policy.outlierMinDistance && add(w,'retained as behavioral outlier',{minGenomeDistanceToActive:minDistance,peakProcesses:peak,opcodeCounts:w.semantic.opcodeCounts,currentLeagueRecord:w.record,summary:`genome distance to active field: ${minDistance.toFixed(2)}; peak processes: ${peak}; current league record: ${recordString(w.record)}`}).ok) outliers++;}
  let favored=0; for(const wanted of humanFavored){const w=candidates.find(c=>c.id===wanted||c.name===wanted||c.displayName===wanted||c.sourcePath===wanted); if(w&&favored<policy.humanFavoredSlots&&add(w,'retained as human-favored specimen',{humanDirection:wanted,summary:`human direction: ${wanted}; reason: manual breeding direction for this epoch`}).ok) favored++;}
  for(const w of candidates){if(selected.length>=policy.populationSize) break; add(w,'retained as roster fill after evidence lanes',{currentLeagueRecord:w.record,benchmarkRecord:w.benchmarkRecord,currentLeagueRank:w.currentLeagueRank,summary:`current league rank #${w.currentLeagueRank}; current league record: ${recordString(w.record)}`});}
  const selectedIds=new Set(selected.map(w=>w.id)); const retiredIds=new Set(retired.map(w=>w.id)); for(const w of candidates){if(selectedIds.has(w.id)||retiredIds.has(w.id)) continue; const near=nearDuplicateOf(w,selected,policy); const reason=near?`near-duplicate pressure against retained ${near.id}`:'active roster cutoff'; retired.push({id:w.id,genomeHash:w.genomeHash,status:'archived',retirementReason:reason,currentLeagueRank:w.currentLeagueRank,record:w.record});}
  return {schemaVersion:1,policy,selected,retired,leaderId:leader?.id};
}
