import {getProfile,mod,RNG} from './profiles.mjs';
import {parseRedcode} from './redcode-parser.mjs';
const dat=()=>({opcode:'DAT',modifier:'F',a:{mode:'#',value:0},b:{mode:'#',value:0},owner:null});
export function runMatch({profileId='kennel94',warriors,seed='match',recordEvents=true,maxCycles}={}){const p=getProfile(profileId); if(warriors.length!==2) throw Error('This first-pass VM supports exactly two warriors'); const parsed=warriors.map((w,i)=>typeof w.source==='string'?parseRedcode(w.source,{profileId,id:w.id||`w${i}`}):w); const rng=new RNG(seed); const core=Array.from({length:p.coreSize},dat); const placements=place(parsed,p,rng); const queues=[[],[]]; const events=[]; parsed.forEach((w,wi)=>{w.instructions.forEach((ins,j)=>core[mod(placements[wi]+j,p.coreSize)]={...clone(ins),owner:wi}); queues[wi].push(mod(placements[wi]+w.start,p.coreSize));}); let cycles=0, winner=null; const limit=maxCycles||p.maxCycles;
 while(cycles<limit && queues.some(q=>q.length)){const wi=cycles%2; if(!queues[wi].length){cycles++; continue;} const pc=queues[wi].shift(); const ins=clone(core[pc]); const ev={c:cycles,warrior:wi,pc,op:ins.opcode,write:[],spawn:null,death:false,queues:queues.map(q=>q.length)}; const next=mod(pc+1,p.coreSize); const A=addr(core,pc,ins.a,p), B=addr(core,pc,ins.b,p); let adv=true;
 switch(ins.opcode){case'DAT':ev.death=true; adv=false; break; case'NOP':break; case'MOV': write(core,B,val(core,pc,ins.a,p),wi,ev); break; case'ADD': math(core,B,val(core,pc,ins.a,p),1,wi,ev,p); break; case'SUB': math(core,B,val(core,pc,ins.a,p),-1,wi,ev,p); break; case'JMP': queues[wi].push(A); adv=false; break; case'JMZ': if(core[B].b.value===0){queues[wi].push(A); adv=false;} break; case'JMN': if(core[B].b.value!==0){queues[wi].push(A); adv=false;} break; case'DJN': core[B].b.value=mod(core[B].b.value-1,p.coreSize); ev.write.push({at:B,owner:wi}); if(core[B].b.value!==0){queues[wi].push(A); adv=false;} break; case'SPL': if(queues[wi].length<p.maxProcesses){queues[wi].push(A); ev.spawn=A;} break; case'CMP': case'SEQ': if(eq(val(core,pc,ins.a,p),val(core,pc,ins.b,p))) queues[wi].push(mod(pc+2,p.coreSize)), adv=false; break; case'SNE': if(!eq(val(core,pc,ins.a,p),val(core,pc,ins.b,p))) queues[wi].push(mod(pc+2,p.coreSize)), adv=false; break; case'SLT': if(val(core,pc,ins.a,p).b.value<val(core,pc,ins.b,p).b.value) queues[wi].push(mod(pc+2,p.coreSize)), adv=false; break; default: throw Error('bad opcode '+ins.opcode);} if(adv&&!ev.death) queues[wi].push(next); if(recordEvents&&(ev.write.length||ev.spawn!==null||ev.death||cycles<80||cycles%50===0)) events.push(ev); cycles++;}
 if(queues[0].length&&!queues[1].length) winner=0; else if(queues[1].length&&!queues[0].length) winner=1; return {profileId,seed,placements,cycles,winner,result:winner===null?'tie':`w${winner}`,events,finalProcessCounts:queues.map(q=>q.length)};}
function place(ws,p,rng){const a=rng.int(p.coreSize); for(let i=0;i<1000;i++){const b=rng.int(p.coreSize); if(Math.abs(b-a)>=p.minSeparation && Math.abs(b-a)<=p.coreSize-p.minSeparation) return [a,b];} return [0,Math.floor(p.coreSize/2)];}
function clone(x){return JSON.parse(JSON.stringify(x));} function write(c,i,v,o,e){c[i]={...clone(v),owner:o}; e.write.push({at:i,owner:o});}
function addr(c,pc,o,p){if(o.mode==='#') return pc; let base=mod(pc+o.value,p.coreSize); if(o.mode==='@') return mod(base+c[base].b.value,p.coreSize); if(o.mode==='<'){c[base].b.value=mod(c[base].b.value-1,p.coreSize); return mod(base+c[base].b.value,p.coreSize);} if(o.mode==='>'){const r=mod(base+c[base].b.value,p.coreSize); c[base].b.value=mod(c[base].b.value+1,p.coreSize); return r;} return base;}
function val(c,pc,o,p){return o.mode==='#'?{opcode:'DAT',modifier:'F',a:{mode:'#',value:0},b:{mode:'#',value:o.value}}:clone(c[addr(c,pc,o,p)]);} function math(c,i,v,s,o,e,p){c[i].a.value=mod(c[i].a.value+s*v.a.value,p.coreSize); c[i].b.value=mod(c[i].b.value+s*v.b.value,p.coreSize); c[i].owner=o; e.write.push({at:i,owner:o});} function eq(x,y){return JSON.stringify(x)===JSON.stringify(y);}
